### ISSUE TITLE
Application for Membership to Founders & Coders Nazareth

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/nazareth-membership#1]
@des-des this is a copy of what `london-membership` has drafted. 

https://docs.google.com/forms/d/1cmVOd_hW8Xx7R1QvUdymXBgX-j1bdBCZpHgabVt-4iI/edit?usp=sharing

If we are happy with this, I suggest we send it to all students/mentors who have attended at least two meetings so they can become full members at the April meeting.

**Comment by rebeccaradding** [comment]
@rebeccaradding will send this form to all who are eligible.

**Comment by des-des** [comment]
Would be happy for this too be sent to all eligable

**Comment by rebeccaradding** [comment]
Closing as we have decided not to use the application form but rather a PR to the register.
